#!/usr/bin/env bash

function loop {
    LOOPSTATUS=$(playerctl loop)
    if [[ $LOOPSTATUS == 'None'     ]]; then playerctl loop Track; fi
    if [[ $LOOPSTATUS == 'Track'    ]]; then playerctl loop Playlist; fi
    if [[ $LOOPSTATUS == 'Playlist' ]]; then playerctl loop None; fi
}

if [[ $1 == 'up' ]];   then playerctl next; fi
if [[ $1 == 'down' ]]; then playerctl previous; fi
if [[ $1 == 'next' ]]; then playerctl next; fi
if [[ $1 == 'prev' ]]; then playerctl previous; fi
if [[ $1 == 'play-pause' ]]; then playerctl play-pause; fi
if [[ $1 == 'loop' ]];     then loop; fi
if [[ $1 == 'shuffle' ]];  then playerctl shuffle Toggle; fi
if [[ $1 == 'volume' ]];   then playerctl volume "0.$2"; fi
if [[ $1 == 'position' && ! -z $2 ]]; then playerctl position $3; fi